[project]
name = "optics-framework-lsp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bishwa Bhusan Saha", email = "77796630+kun-codes@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pygls>=2.1.1",
    "pyyaml>=6.0.3",
]

[project.scripts]
optics-lsp = "optics_framework_lsp.cli:main"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-lsp>=1.0.1",
]
