# GENERATED — do not edit. Run `python scripts/update_catalog.py` to refresh.
#
# Keyword signatures read from optics-framework 1.9.3. `required` counts the leading
# positional params with no default; `variadic` means the keyword takes `*args`, so any
# number of params is legal.

OPTICS_VERSION = '1.9.3'

KEYWORDS: dict[str, dict] = {
    'assert equality': {
        'required': 2,
        'variadic': False,
        'params': ['output', 'expression', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Compares two values for equality. Both values are resolved from session\nelements if they are ``${variable}`` references before comparison.\n\n:param output: The actual value or ``${variable}`` reference.\n:param expression: The expected value or ``${variable}`` reference.\n:param event_name: The name of the event associated with the comparison, if any.\n:return: True if equal, False otherwise.',
    },
    'assert presence': {
        'required': 1,
        'variadic': False,
        'params': ['elements', 'timeout_str', 'rule', 'event_name', 'fail'],
        'defaults': {'timeout_str': "'30'", 'rule': "'any'", 'event_name': 'None', 'fail': 'True'},
        'doc': 'Asserts the presence of elements -- anywhere in the page/DOM, visible or not.\n\n:param elements: Comma-separated string of elements to check (Image templates, OCR templates, or XPaths).\n:param timeout: The time to wait for the elements in seconds.\n:param rule: The rule for verification ("any" or "all").\n:param event_name: The name of the event associated with the assertion, if any.\n:return: True if the rule is satisfied, False otherwise.',
    },
    'assert visibility': {
        'required': 1,
        'variadic': False,
        'params': ['elements', 'timeout_str', 'rule', 'event_name', 'fail'],
        'defaults': {'timeout_str': "'30'", 'rule': "'any'", 'event_name': 'None', 'fail': 'True'},
        'doc': 'Asserts that elements are actually rendered/visible on screen right now -- distinct\nfrom :meth:`assert_presence`, which reports found even for elements that exist in\nthe page/DOM but are off-screen (e.g. not yet scrolled into view).\n\n:param elements: Comma-separated string of elements to check (Image templates, OCR templates, or XPaths).\n:param timeout_str: The time to wait for the elements to become visible, in seconds.\n:param rule: The rule for verification ("any" or "all").\n:param event_name: The name of the event associated with the assertion, if any.\n:return: True if the rule is satisfied, False otherwise.',
    },
    'capture pagesource': {
        'required': 0,
        'variadic': False,
        'params': ['event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Captures the page source and timestamp of the current screen.\n\n:param event_name: The name of the event associated with the page source capture, if any.\n:return: Dict with "page_source" and "timestamp" keys.',
    },
    'capture screenshot': {
        'required': 0,
        'variadic': False,
        'params': ['event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Captures a screenshot of the current screen.\n\n:param event_name: The name of the event associated with the screenshot capture, if any.\n:return: The path to the captured screenshot.',
    },
    'clear element text': {
        'required': 1,
        'variadic': False,
        'params': ['element', 'aoi_x', 'aoi_y', 'aoi_width', 'aoi_height', 'event_name'],
        'defaults': {'aoi_x': "'0'", 'aoi_y': "'0'", 'aoi_width': "'100'", 'aoi_height': "'100'", 'event_name': 'None'},
        'doc': 'Clear text from a specified element.\n\n:param element: The target element (Image template, OCR template, or XPath).\n:param aoi_x: X percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_y: Y percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_width: Width percentage of Area of Interest (0-100). Default: 100.\n:param aoi_height: Height percentage of Area of Interest (0-100). Default: 100.\n:param event_name: The event triggering the action.',
    },
    'close and terminate app': {
        'required': 0,
        'variadic': False,
        'params': [],
        'defaults': {},
        'doc': 'Tears down the active driver session and flushes all pending events.\n\nBehaviour depends on the configured driver: WebDriver-based drivers\n(Appium, Selenium) call quit(); Playwright closes the page, context,\nand browser; BLE closes the serial port. All variants flush pending\nEventSDK events and release the driver reference.',
    },
    'condition': {
        'required': 0,
        'variadic': True,
        'params': [],
        'defaults': {},
        'doc': 'Evaluates conditions and executes corresponding targets.',
    },
    'date evaluate': {
        'required': 3,
        'variadic': False,
        'params': ['param1', 'param2', 'param3', 'param4'],
        'defaults': {'param4': "'%d %B'"},
        'doc': 'Evaluates a date expression based on an input date and stores the result in session.elements.\n\nArgs:\n    param1 (str): The variable name (placeholder) where the evaluated date result will be stored.\n    param2 (str): The input date string (e.g., "04/25/2025" or "2025-04-25"). Format is auto-detected.\n    param3 (str): The date expression to evaluate, such as "+1 day", "-2 days", or "today".\n    param4 (Optional[str]): The output format for the evaluated date (default is "%d %B", e.g., "26 April").\n\nReturns:\n    str: The resulting evaluated and formatted date string.\n\nRaises:\n    ValueError: If the session is not present, the input date format cannot be detected,\n                or the expression format is invalid.\n\nExample:\n    date_evaluate("tomorrow", "04/25/2025", "+1 day")\n    ➔ Stores "26 April" in session.elements["tomorrow"]',
    },
    'detect and press': {
        'required': 1,
        'variadic': False,
        'params': ['element', 'timeout', 'event_name'],
        'defaults': {'timeout': "'30'", 'event_name': 'None'},
        'doc': 'Detect and press a specified element.\n\n:param element: The element to be detected and pressed (Image template, OCR template, or XPath).\n:param timeout: Timeout for the detection operation.\n:param event_name: The event triggering the press.',
    },
    'enter number': {
        'required': 2,
        'variadic': False,
        'params': ['element', 'number', 'aoi_x', 'aoi_y', 'aoi_width', 'aoi_height', 'event_name'],
        'defaults': {'aoi_x': "'0'", 'aoi_y': "'0'", 'aoi_width': "'100'", 'aoi_height': "'100'", 'event_name': 'None'},
        'doc': 'Enter a specified number into an element.\n\n:param element: The target element (Image template, OCR template, or XPath).\n:param number: The number to be entered.\n:param aoi_x: X percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_y: Y percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_width: Width percentage of Area of Interest (0-100). Default: 100.\n:param aoi_height: Height percentage of Area of Interest (0-100). Default: 100.\n:param event_name: The event triggering the input.',
    },
    'enter text': {
        'required': 2,
        'variadic': False,
        'params': ['element', 'text', 'aoi_x', 'aoi_y', 'aoi_width', 'aoi_height', 'event_name'],
        'defaults': {'aoi_x': "'0'", 'aoi_y': "'0'", 'aoi_width': "'100'", 'aoi_height': "'100'", 'event_name': 'None'},
        'doc': 'Enter text into a specified element.\n\n:param element: The target element (Image template, OCR template, or XPath).\n:param text: The text to be entered.\n:param aoi_x: X percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_y: Y percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_width: Width percentage of Area of Interest (0-100). Default: 100.\n:param aoi_height: Height percentage of Area of Interest (0-100). Default: 100.\n:param event_name: The event triggering the input.',
    },
    'enter text direct': {
        'required': 1,
        'variadic': False,
        'params': ['text', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Enter text using the keyboard.\n\n:param text: The text to be entered.\n:param event_name: The event triggering the input.',
    },
    'enter text using keyboard': {
        'required': 1,
        'variadic': False,
        'params': ['text_input', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': "Enter text or press a special key using the keyboard.\n\nIf the input is a string that includes angle brackets (e.g., '<enter>'),\nthe text between the brackets will be interpreted as a special key name and mapped accordingly.\n\n:param input: The text or special key identifier to send.\n:param event_name: Optional event label for logging.",
    },
    'evaluate': {
        'required': 2,
        'variadic': False,
        'params': ['param1', 'param2'],
        'defaults': {},
        'doc': 'Evaluates an expression and stores the result in session.elements.',
    },
    'execute module': {
        'required': 1,
        'variadic': False,
        'params': ['module_name'],
        'defaults': {},
        'doc': "Executes a module's keywords using the session's keyword_map.\n\nNot exposed on the Optics SDK — session.modules is only populated by\nCSV/YAML-driven execution; SDK/Robot Framework users should call keywords\ndirectly or write a real function/keyword instead.",
    },
    'execute script': {
        'required': 1,
        'variadic': False,
        'params': ['script_or_json', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Execute JavaScript/script in the current context.\n\n:param script_or_json: The JavaScript code/script command, or a JSON string containing\n                       {"script": "...", "args": {...}} or {"script": "..."}.\n                       Examples:\n                       - "mobile:pressKey" (plain script)\n                       - \'{"script": "mobile:pressKey", "args": {"keycode": 3}}\' (JSON with args)\n                       - \'{"script": "mobile:clear"}\' (JSON without args)\n:type script_or_json: str\n:param event_name: The event triggering the script execution, if any.\n:type event_name: Optional[str]\n:return: The result of the script execution.\n:rtype: Any',
    },
    'force terminate app': {
        'required': 1,
        'variadic': False,
        'params': ['app_name', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Forcefully terminates the specified application.\n\n:param app_name: The name of the application to terminate.\n:param event_name: The event triggering the forced termination, if any.',
    },
    'get app version': {
        'required': 0,
        'variadic': False,
        'params': ['app_package'],
        'defaults': {'app_package': 'None'},
        'doc': 'Gets the version of the application.\n\n:return: The version of the application, or None if not available.',
    },
    'get driver session id': {
        'required': 0,
        'variadic': False,
        'params': [],
        'defaults': {},
        'doc': 'Return the current driver session id, if available.',
    },
    'get interactive elements': {
        'required': 0,
        'variadic': False,
        'params': ['filter_config'],
        'defaults': {'filter_config': 'None'},
        'doc': 'Retrieves a list of interactive elements on the current screen.\n\nXPath and text fields are converted to one-line, CSV-friendly form (newlines\nas \\n, tabs as \\t, etc.) so output can be pasted into elements.csv or similar.\nOn Appium sources, element bounds are returned in the screenshot\'s pixel space.\n\n:param filter_config: Optional list of filter types (e.g., ["buttons", "inputs"]).\n:type filter_config: Optional[List[str]]\n:return: A list of interactive elements.',
    },
    'get screen elements': {
        'required': 0,
        'variadic': False,
        'params': [],
        'defaults': {},
        'doc': "Captures a screenshot and retrieves interactive elements for API response.\n\nBounds are scaled to the returned screenshot's pixel space using a single\ncapture shared between the image and the bounds, so callers can overlay the\nbounds on the screenshot without any scaling of their own.\n\n:return: Dict with base64-encoded screenshot and list of elements.",
    },
    'get text': {
        'required': 1,
        'variadic': False,
        'params': ['element'],
        'defaults': {},
        'doc': 'Get the text from a specified element.\n\n:param element: The target element (Image template, OCR template, or XPath).\n:return: The text from the element or None if not supported.',
    },
    'initialise setup': {
        'required': 0,
        'variadic': False,
        'params': [],
        'defaults': {},
        'doc': "Sets up the environment for the driver module.\n\nThis method should be called before performing any application\nmanagement operations.\n\nNot exposed on the Optics SDK because it currently performs no operation and doesn't\ndelegate to the driver's own initialise_setup (e.g. AppiumDriver.initialise_setup).",
    },
    'invoke api': {
        'required': 1,
        'variadic': False,
        'params': ['api_identifier'],
        'defaults': {},
        'doc': "Invokes an API call based on a definition from the session's API data.",
    },
    'is element': {
        'required': 3,
        'variadic': False,
        'params': ['element', 'element_state', 'timeout', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Checks if the specified element is in a given state (e.g., Enabled/Disabled/Visible/Invisible).\n\n:param element: The element to be checked (Image template, OCR template, or XPath).\n:param element_state: The state to verify (visible, invisible, enabled, disabled).\n:param timeout: The time to wait for the element in seconds.\n:param event_name: The name of the event associated with the check, if any.',
    },
    'launch app': {
        'required': 0,
        'variadic': False,
        'params': ['app_identifier', 'app_activity', 'event_name'],
        'defaults': {'app_identifier': 'None', 'app_activity': 'None', 'event_name': 'None'},
        'doc': 'Launches the specified application.\n\n:param event_name: The event triggering the app launch, if any.',
    },
    'launch other app': {
        'required': 1,
        'variadic': False,
        'params': ['app_name', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Starts another application.\n\n:param package_name: The package name of the application.\n:param event_name: The event triggering the app start, if any.',
    },
    'press by coordinates': {
        'required': 2,
        'variadic': False,
        'params': ['coor_x', 'coor_y', 'repeat', 'event_name'],
        'defaults': {'repeat': "'1'", 'event_name': 'None'},
        'doc': 'Press an element by absolute coordinates.\n\n:param coor_x: X coordinate of the press.\n:param coor_y: Y coordinate of the press.\n:param repeat: Number of times to repeat the press.\n:param event_name: The event triggering the press.',
    },
    'press by percentage': {
        'required': 2,
        'variadic': False,
        'params': ['percent_x', 'percent_y', 'repeat', 'event_name'],
        'defaults': {'repeat': "'1'", 'event_name': 'None'},
        'doc': 'Press an element by percentage coordinates.\n\n:param percent_x: X percentage of the press (as string, will be converted to float).\n:param percent_y: Y percentage of the press (as string, will be converted to float).\n:param repeat: Number of times to repeat the press.\n:param event_name: The event triggering the press.',
    },
    'press checkbox': {
        'required': 1,
        'variadic': False,
        'params': ['element', 'aoi_x', 'aoi_y', 'aoi_width', 'aoi_height', 'event_name'],
        'defaults': {'aoi_x': "'0'", 'aoi_y': "'0'", 'aoi_width': "'100'", 'aoi_height': "'100'", 'event_name': 'None'},
        'doc': 'Press a specified checkbox element.\n\n.. deprecated:: Deprecated alias of :meth:`press_element` — use ``Press Element`` directly.\n\n:param element: The checkbox element (Image template, OCR template, or XPath).\n:param aoi_x: X percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_y: Y percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_width: Width percentage of Area of Interest (0-100). Default: 100.\n:param aoi_height: Height percentage of Area of Interest (0-100). Default: 100.\n:param event_name: The event triggering the press.',
    },
    'press element': {
        'required': 1,
        'variadic': False,
        'params': ['element', 'repeat', 'offset_x', 'offset_y', 'index', 'aoi_x', 'aoi_y', 'aoi_width', 'aoi_height', 'event_name'],
        'defaults': {'repeat': "'1'", 'offset_x': "'0'", 'offset_y': "'0'", 'index': "'0'", 'aoi_x': "'0'", 'aoi_y': "'0'", 'aoi_width': "'100'", 'aoi_height': "'100'", 'event_name': 'None'},
        'doc': 'Press a specified element.\n\n:param element: The element to be pressed (text, xpath or image).\n:param repeat: Number of times to repeat the press.\n:param offset_x: X offset of the press.\n:param offset_y: Y offset of the press.\n:param index: Index of the element if multiple matches are found.\n:param event_name: The event triggering the press.\n:param aoi_x: X percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_y: Y percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_width: Width percentage of Area of Interest (0-100). Default: 100.\n:param aoi_height: Height percentage of Area of Interest (0-100). Default: 100.',
    },
    'press keycode': {
        'required': 1,
        'variadic': False,
        'params': ['keycode', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Press a specified keycode.\n\n:param keycode: The keycode to be pressed.\n:param event_name: The event triggering the press.',
    },
    'press radio button': {
        'required': 1,
        'variadic': False,
        'params': ['element', 'aoi_x', 'aoi_y', 'aoi_width', 'aoi_height', 'event_name'],
        'defaults': {'aoi_x': "'0'", 'aoi_y': "'0'", 'aoi_width': "'100'", 'aoi_height': "'100'", 'event_name': 'None'},
        'doc': 'Press a specified radio button.\n\n.. deprecated:: Deprecated alias of :meth:`press_element` — use ``Press Element`` directly.\n\n:param element: The radio button element (Image template, OCR template, or XPath).\n:param aoi_x: X percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_y: Y percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_width: Width percentage of Area of Interest (0-100). Default: 100.\n:param aoi_height: Height percentage of Area of Interest (0-100). Default: 100.\n:param event_name: The event triggering the press.',
    },
    'read data': {
        'required': 2,
        'variadic': False,
        'params': ['input_element', 'file_path', 'query'],
        'defaults': {'query': "''"},
        'doc': 'Reads tabular data from a CSV file, JSON file, environment variable, or a 2D list,\napplies optional filtering and column selection, and stores the result in the session\'s elements.\n\nArgs:\n    input_element: Variable name where the result is stored (e.g. `${data}`). Prefer `${name}` form.\n    file_path: Data source. One of: (1) path to a `.csv` or `.json` file; (2) string\n        ``ENV:VAR_NAME`` to use an environment variable (value parsed as JSON, CSV, or plain string);\n        (3) a 2D list with first row as headers (Python API only).\n    query: Optional semicolon-separated parts: ``select=col1,col2`` and/or filter expressions\n        (pandas-style). Any ``${varname}`` in the query is resolved from `session.elements` before\n        evaluation. Default ``""``.\n\nReturns:\n    The stored value as a list (or list of lists for multi-row results). Also writes into\n    `session.elements` under the name derived from `input_element`.',
    },
    'run loop': {
        'required': 1,
        'variadic': True,
        'params': ['target'],
        'defaults': {},
        'doc': 'Runs a loop over a target module, either by count or with variables.',
    },
    'scroll': {
        'required': 1,
        'variadic': False,
        'params': ['direction', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Perform a scroll action in a specified direction.\n\n:param direction: The scroll direction (up, down, left, right).\n:param event_name: The event triggering the scroll.',
    },
    'scroll from element': {
        'required': 3,
        'variadic': False,
        'params': ['element', 'direction', 'scroll_length', 'aoi_x', 'aoi_y', 'aoi_width', 'aoi_height', 'event_name'],
        'defaults': {'aoi_x': "'0'", 'aoi_y': "'0'", 'aoi_width': "'100'", 'aoi_height': "'100'", 'event_name': 'None'},
        'doc': 'Perform a scroll action starting from a specified element.\n\n:param element: The element to scroll from (Image template, OCR template, or XPath).\n:param direction: The scroll direction (up, down, left, right).\n:param scroll_length: The length of the scroll.\n:param aoi_x: X percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_y: Y percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_width: Width percentage of Area of Interest (0-100). Default: 100.\n:param aoi_height: Height percentage of Area of Interest (0-100). Default: 100.\n:param event_name: The event triggering the scroll.',
    },
    'scroll until element appears': {
        'required': 3,
        'variadic': False,
        'params': ['element', 'direction', 'timeout', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Scroll in a specified direction until an element appears.\n\n:param element: The target element (Image template, OCR template, or XPath).\n:param direction: The scroll direction (up, down, left, right).\n:param timeout: Timeout for the scroll operation.\n:param event_name: The event triggering the scroll.',
    },
    'select dropdown option': {
        'required': 2,
        'variadic': False,
        'params': ['element', 'option', 'timeout', 'event_name'],
        'defaults': {'timeout': "'30'", 'event_name': 'None'},
        'doc': "Open a dropdown and select one of its options, scrolling through the list if needed.\n\nOpens the dropdown by pressing `element`. If `option` isn't visible right away,\ndiffs the interactive elements captured before and after opening to find the\ndropdown's list container, then scrolls within that container (never past the page\nbehind it) until `option` appears or the list stops changing. Raises `OpticsError`\n(`E0201``) if `option` is never found within `timeout` seconds.\n\nFalls back to a single-screen check (no scrolling) when page source, or a list-like\ncontainer, isn't available.\n\nAssumption: opened dropdown list is opened in such a way that the topmost option is\nvisible on the screen\n\n:param element: The dropdown element (Image template, OCR template, or XPath).\n:param option: The option to select (visible label, OCR/Image template, or XPath).\n:param timeout: Seconds to keep scrolling through the dropdown list before failing.\n:param event_name: The event triggering the selection.",
    },
    'sleep': {
        'required': 1,
        'variadic': False,
        'params': ['duration'],
        'defaults': {},
        'doc': 'Sleep for a specified duration.\n\n:param duration: The duration of the sleep in seconds.',
    },
    'start appium session': {
        'required': 0,
        'variadic': False,
        'params': ['event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Starts an Appium session.\n\n:param event_name: The event triggering the session start, if any.',
    },
    'swipe': {
        'required': 2,
        'variadic': False,
        'params': ['coor_x', 'coor_y', 'direction', 'swipe_length', 'event_name'],
        'defaults': {'direction': "'right'", 'swipe_length': "'50'", 'event_name': 'None'},
        'doc': 'Perform a swipe action in a specified direction.\n\n:param coor_x: X coordinate of the swipe.\n:param coor_y: Y coordinate of the swipe.\n:param direction: The swipe direction (up, down, left, right).\n:param swipe_length: The length of the swipe.\n:param event_name: The event triggering the swipe.',
    },
    'swipe by percentage': {
        'required': 2,
        'variadic': False,
        'params': ['percent_x', 'percent_y', 'direction', 'swipe_length', 'event_name'],
        'defaults': {'direction': "'right'", 'swipe_length': "'50'", 'event_name': 'None'},
        'doc': 'Perform a swipe action in a specified direction by percentage.\n\n:param percent_x: X percentage of the swipe.\n:param percent_y: Y percentage of the swipe.\n:param direction: The swipe direction (up, down, left, right).\n:param swipe_length: The length of the swipe.\n:param event_name: The event triggering the swipe.',
    },
    'swipe from element': {
        'required': 3,
        'variadic': False,
        'params': ['element', 'direction', 'swipe_length', 'aoi_x', 'aoi_y', 'aoi_width', 'aoi_height', 'event_name'],
        'defaults': {'aoi_x': "'0'", 'aoi_y': "'0'", 'aoi_width': "'100'", 'aoi_height': "'100'", 'event_name': 'None'},
        'doc': 'Perform a swipe action starting from a specified element.\n\n:param element: The element to swipe from (Image template, OCR template, or XPath).\n:param direction: The swipe direction (up, down, left, right).\n:param swipe_length: The length of the swipe.\n:param aoi_x: X percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_y: Y percentage of Area of Interest top-left corner (0-100). Default: 0.\n:param aoi_width: Width percentage of Area of Interest (0-100). Default: 100.\n:param aoi_height: Height percentage of Area of Interest (0-100). Default: 100.\n:param event_name: The event triggering the swipe.',
    },
    'swipe seekbar to right android': {
        'required': 1,
        'variadic': False,
        'params': ['element', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Swipe a seekbar to the right.\n\n.. deprecated:: Deprecated; prefer :meth:`swipe_from_element` / :meth:`swipe`.\n\n:param element: The seekbar element (Image template, OCR template, or XPath).',
    },
    'swipe until element appears': {
        'required': 3,
        'variadic': False,
        'params': ['element', 'direction', 'timeout', 'event_name'],
        'defaults': {'event_name': 'None'},
        'doc': 'Swipe in a specified direction until an element appears.\n\n:param element: The target element (Image template, OCR template, or XPath).\n:param direction: The swipe direction (up, down, left, right).\n:param timeout: Timeout until element search is performed.\n:param event_name: The event triggering the swipe.',
    },
    'validate element': {
        'required': 1,
        'variadic': False,
        'params': ['element', 'timeout', 'rule', 'event_name'],
        'defaults': {'timeout': "'10'", 'rule': "'all'", 'event_name': 'None'},
        'doc': 'Verifies the specified element.\n\n:param element: The element to be verified (Image template, OCR template, or XPath).\n:param timeout: The time to wait for verification in seconds.\n:param rule: The rule used for verification ("all" or "any").\n:param event_name: The name of the event associated with the verification, if any.',
    },
    'validate screen': {
        'required': 1,
        'variadic': False,
        'params': ['elements', 'timeout', 'rule', 'event_name'],
        'defaults': {'timeout': "'30'", 'rule': "'any'", 'event_name': 'None'},
        'doc': 'Verifies the specified screen by checking element presence.\n\n:param elements: Comma-separated string of elements to verify (Image templates, OCR templates, or XPaths).\n:param timeout: The time to wait for verification in seconds.\n:param rule: The rule for verification ("any" or "all").\n:param event_name: The name of the event associated with the verification, if any.',
    },
}
